import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-opencli writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.opencli.mac"
let gatewayLaunchdLabel = "ai.opencli.gateway"
let onboardingVersionKey = "opencli.onboardingVersion"
let onboardingSeenKey = "opencli.onboardingSeen"
let currentOnboardingVersion = 7
let pauseDefaultsKey = "opencli.pauseEnabled"
let iconAnimationsEnabledKey = "opencli.iconAnimationsEnabled"
let swabbleEnabledKey = "opencli.swabbleEnabled"
let swabbleTriggersKey = "opencli.swabbleTriggers"
let voiceWakeTriggerChimeKey = "opencli.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "opencli.voiceWakeSendChime"
let showDockIconKey = "opencli.showDockIcon"
let defaultVoiceWakeTriggers = ["opencli"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "opencli.voiceWakeMicID"
let voiceWakeMicNameKey = "opencli.voiceWakeMicName"
let voiceWakeLocaleKey = "opencli.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "opencli.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "opencli.voicePushToTalkEnabled"
let voiceWakeTriggersTalkModeKey = "opencli.voiceWakeTriggersTalkMode"
let talkEnabledKey = "opencli.talkEnabled"
let talkPhaseSoundsEnabledKey = "opencli.talkPhaseSoundsEnabled"
let talkShiftToStopEnabledKey = "opencli.talkShiftToStopEnabled"
let iconOverrideKey = "opencli.iconOverride"
let connectionModeKey = "opencli.connectionMode"
let remoteTargetKey = "opencli.remoteTarget"
let remoteIdentityKey = "opencli.remoteIdentity"
let remoteProjectRootKey = "opencli.remoteProjectRoot"
let remoteCliPathKey = "opencli.remoteCliPath"
let canvasEnabledKey = "opencli.canvasEnabled"
let cameraEnabledKey = "opencli.cameraEnabled"
let systemRunPolicyKey = "opencli.systemRunPolicy"
let systemRunAllowlistKey = "opencli.systemRunAllowlist"
let systemRunEnabledKey = "opencli.systemRunEnabled"
let locationModeKey = "opencli.locationMode"
let locationPreciseKey = "opencli.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "opencli.peekabooBridgeEnabled"
let deepLinkKeyKey = "opencli.deepLinkKey"
let modelCatalogPathKey = "opencli.modelCatalogPath"
let modelCatalogReloadKey = "opencli.modelCatalogReload"
let cliInstallPromptedVersionKey = "opencli.cliInstallPromptedVersion"
let heartbeatsEnabledKey = "opencli.heartbeatsEnabled"
let debugPaneEnabledKey = "opencli.debugPaneEnabled"
let debugFileLogEnabledKey = "opencli.debug.fileLogEnabled"
let appLogLevelKey = "opencli.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
