#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/lib/docker-build.sh"
IMAGE_NAME="${OPENCLI_INSTALL_E2E_IMAGE:-opencli-install-e2e:local}"
INSTALL_URL="${OPENCLI_INSTALL_URL:-https://opencli.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
OPENCLI_E2E_MODELS="${OPENCLI_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker_build_run install-e2e-build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e OPENCLI_INSTALL_URL="$INSTALL_URL" \
  -e OPENCLI_INSTALL_TAG="${OPENCLI_INSTALL_TAG:-latest}" \
  -e OPENCLI_E2E_MODELS="$OPENCLI_E2E_MODELS" \
  -e OPENCLI_INSTALL_E2E_PREVIOUS="${OPENCLI_INSTALL_E2E_PREVIOUS:-}" \
  -e OPENCLI_INSTALL_E2E_SKIP_PREVIOUS="${OPENCLI_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e OPENCLI_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS="${OPENCLI_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS:-600}" \
  -e OPENCLI_INSTALL_E2E_AGENT_TURNS_PARALLEL="${OPENCLI_INSTALL_E2E_AGENT_TURNS_PARALLEL:-1}" \
  -e OPENCLI_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
