export const browserCoreExamples = [
  "opencli browser status",
  "opencli browser start",
  "opencli browser start --headless",
  "opencli browser stop",
  "opencli browser tabs",
  "opencli browser open https://example.com",
  "opencli browser focus abcd1234",
  "opencli browser close abcd1234",
  "opencli browser screenshot",
  "opencli browser screenshot --full-page",
  "opencli browser screenshot --ref 12",
  "opencli browser snapshot",
  "opencli browser snapshot --format aria --limit 200",
  "opencli browser snapshot --efficient",
  "opencli browser snapshot --labels",
];

export const browserActionExamples = [
  "opencli browser navigate https://example.com",
  "opencli browser resize 1280 720",
  "opencli browser click 12 --double",
  "opencli browser click-coords 120 340",
  'opencli browser type 23 "hello" --submit',
  "opencli browser press Enter",
  "opencli browser hover 44",
  "opencli browser drag 10 11",
  "opencli browser select 9 OptionA OptionB",
  "opencli browser upload /tmp/opencli/uploads/file.pdf",
  'opencli browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opencli browser dialog --accept",
  'opencli browser wait --text "Done"',
  "opencli browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opencli browser console --level error",
  "opencli browser pdf",
];
